del lbc*
type ch1.txt >> lbc.txt
type ch2.txt >> lbc.txt
type ch3.txt >> lbc.txt
type ch4.txt >> lbc.txt
type ch5.txt >> lbc.txt
type ch6.txt >> lbc.txt
type ch7.txt >> lbc.txt
type ch8.txt >> lbc.txt
type ch9.txt >> lbc.txt
type ch10.txt >> lbc.txt
type ch11.txt >> lbc.txt
type ch12.txt >> lbc.txt
type ch13.txt >> lbc.txt
type ch14.txt >> lbc.txt
type ch15.txt >> lbc.txt
type ch16.txt >> lbc.txt
type ch17.txt >> lbc.txt
type ch18.txt >> lbc.txt
type ch19.txt >> lbc.txt
type ch20.txt >> lbc.txt
type ch21.txt >> lbc.txt
type ch22.txt >> lbc.txt
type ch23.txt >> lbc.txt
type ch24.txt >> lbc.txt
type ch25.txt >> lbc.txt
type ch26.txt >> lbc.txt
type ch27.txt >> lbc.txt
type ch28.txt >> lbc.txt
type ch29.txt >> lbc.txt
type ch30.txt >> lbc.txt
type ch31.txt >> lbc.txt
type ch32.txt >> lbc.txt